# Generated by Django 5.2.14 on 2026-05-20 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem_url', models.CharField(blank=True, max_length=500, null=True)),
                ('gif_url', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('equipamento', models.CharField(blank=True, max_length=60, null=True)),
                ('categoria', models.CharField(blank=True, max_length=60, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Músculo',
                'verbose_name_plural': 'Músculos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.SmallIntegerField()),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('repeticoes', models.SmallIntegerField(blank=True, null=True)),
                ('tipo_serie', models.CharField(choices=[('NORMAL', 'Normal'), ('AQUECIMENTO', 'Aquecimento'), ('DROP', 'Drop Set'), ('FALHA', 'Até a Falha')], default='NORMAL', max_length=20)),
                ('rr', models.DecimalField(blank=True, decimal_places=2, help_text='RPE/RIR ou outra métrica de esforço', max_digits=5, null=True)),
                ('volume_serie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='SessaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('anotacao_performance', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Exercício na Sessão',
                'verbose_name_plural': 'Exercícios na Sessão',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('volume_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sessão de Treino',
                'verbose_name_plural': 'Sessões de Treino',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='TreinoExercicioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('series_sugeridas', models.SmallIntegerField(blank=True, null=True)),
                ('descanso_segundos', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exercício no Template',
                'verbose_name_plural': 'Exercícios no Template',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TreinoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('is_publico', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Treino',
                'verbose_name_plural': 'Templates de Treino',
            },
        ),
        migrations.CreateModel(
            name='ExercicioMusculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_principal', models.BooleanField(default=False)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
                ('musculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.musculo')),
            ],
        ),
        migrations.AddField(
            model_name='exercicio',
            name='musculos',
            field=models.ManyToManyField(related_name='exercicios', through='treinos.ExercicioMusculo', to='treinos.musculo'),
        ),
        migrations.CreateModel(
            name='RecordePessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_1rm_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maior_peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('data_conquista', models.DateField(auto_now=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
            ],
            options={
                'verbose_name': 'Recorde Pessoal',
                'verbose_name_plural': 'Recordes Pessoais',
            },
        ),
    ]
