# Generated by Django 5.2.14 on 2026-05-20 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treinos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recordepessoal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordes_pessoais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaoexercicio',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio'),
        ),
        migrations.AddField(
            model_name='serie',
            name='sessao_exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='treinos.sessaoexercicio'),
        ),
        migrations.AddField(
            model_name='sessaotreino',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_treino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaoexercicio',
            name='sessao_treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.sessaotreino'),
        ),
        migrations.AddField(
            model_name='treinoexerciciotemplate',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio'),
        ),
        migrations.AddField(
            model_name='treinotemplate',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_template', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treinoexerciciotemplate',
            name='treino_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='treinos.treinotemplate'),
        ),
        migrations.AddField(
            model_name='sessaotreino',
            name='treino_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='treinos.treinotemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='exerciciomusculo',
            unique_together={('exercicio', 'musculo')},
        ),
        migrations.AlterUniqueTogether(
            name='recordepessoal',
            unique_together={('usuario', 'exercicio')},
        ),
    ]
